version: "3.5"
services:
    qnap-pkg-mirror:
        build: .
        restart: always
        ports:
            - 8090:8090
        volumes:
            - ./etc:/opt/QnapPkgMirror/etc
        links:
            - mongo
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
